version: '3'

services:
  cashucache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3338:3338"
    volumes:
      - .:/app
      - ./cashu_data:/root/.cashu
    networks:
      - cachucacher

  wallet:
    build:
      context: https://github.com/cashubtc/nutshell.git
    container_name: nutshell-wallet
    ports:
      - "4448:4448"
    environment:
      - MINT_URL=https://8333.space:3338/
      - API_HOST=0.0.0.0
    volumes:
      - ./cashu_data:/root/.cashu
    networks:
      - cachucacher
    command: ["poetry", "run", "cashu", "-d"]

networks:
  cachucacher:
    driver: bridge
